# Do not set the mtime
--no-mtime

# Download the best available h264 by default
--format-sort "vcodec:h264,res,acodec:m4a"

# Download metadata
--write-info-json
--write-playlist-metafiles

# Download thumbnails
--write-thumbnail
--convert-thumbnails jpg

# Define a temp directory and restrict the filenames
--paths temp:/home/feedme/.yt-dlp/tmp
--restrict-filenames

# Retry forever
--file-access-retries infinite
--fragment-retries infinite

# Parallelize via the built-in parallelizer
--concurrent-fragments 8

# Enable NodeJS; see https://github.com/yt-dlp/yt-dlp/wiki/EJS
--js-runtimes node

# Use cookies file if present
--cookies /home/feedme/cookies.txt
